//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrDetailId
    {
        public int orDetailId1 { get; set; }
        public Nullable<int> SId { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<int> GId { get; set; }
    }
}
