//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderminxi
    {
        public int minxiid { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> snum { get; set; }
        public Nullable<double> sprice { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> isget { get; set; }
    }
}
