//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Splb
    {
        public int splid { get; set; }
        public string neirong { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> gid { get; set; }
        public Nullable<System.DateTime> pltime { get; set; }
        public Nullable<int> state { get; set; }
    }
}
