//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UId { get; set; }
        public string Uname { get; set; }
        public string Sex { get; set; }
        public string Pwd { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string ImgUrl { get; set; }
        public string bankCard { get; set; }
        public string Email { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string truename { get; set; }
    }
}
