//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAdress
    {
        public long ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public string CityName { get; set; }
        public long CityID { get; set; }
        public string DistrictName { get; set; }
        public long DistrictID { get; set; }
    }
}
