//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOrdel
    {
        public string Gpicture { get; set; }
        public Nullable<double> Gprice { get; set; }
        public string Gintroduce { get; set; }
        public Nullable<double> Gnumber { get; set; }
        public Nullable<double> GpNum { get; set; }
        public string Uname { get; set; }
        public string name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string bankCard { get; set; }
        public int UId { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public int orDetailId { get; set; }
        public int SId { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public int Expr2 { get; set; }
        public string Sname { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<decimal> Expr5 { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public Nullable<System.DateTime> Expr7 { get; set; }
        public string Gname { get; set; }
    }
}
